import { OBSTACLE_TYPES } from "./obstacleSpawner.js";

export function initRenderer(canvas) { return canvas.getContext("2d"); }

function roundedRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawBackground(ctx,state){const{width:w,height:h}=ctx.canvas;const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,"#120b38");sky.addColorStop(.55,"#52205d");sky.addColorStop(1,"#11182d");ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle="rgba(249,168,212,.2)";ctx.beginPath();ctx.arc(w*.72,h*.2,72,0,Math.PI*2);ctx.fill();
  const far=(state.elapsed*18)%220;ctx.fillStyle="#21153e";for(let i=-1;i<6;i++){const x=i*220-far;ctx.beginPath();ctx.moveTo(x,h*.7);ctx.lineTo(x+105,h*.31);ctx.lineTo(x+220,h*.7);ctx.fill()}
  const near=(state.elapsed*44)%180;ctx.fillStyle="#17243b";for(let i=-1;i<7;i++){const x=i*180-near;ctx.beginPath();ctx.moveTo(x,h*.74);ctx.lineTo(x+70,h*.48);ctx.lineTo(x+140,h*.74);ctx.fill()}
  ctx.fillStyle="#182337";ctx.fillRect(0,410,w,h-410);ctx.strokeStyle="rgba(34,211,238,.18)";ctx.lineWidth=2;const floor=(state.elapsed*state.speed*.45)%80;for(let x=-floor;x<w;x+=80){ctx.beginPath();ctx.moveTo(x,410);ctx.lineTo(x-90,h);ctx.stroke()}for(let y=430;y<h;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}

function drawRunner(ctx,p,t){const squat=p.action==="squat"&&p.grounded;const bob=p.grounded?Math.sin(t*12)*3:0;const x=p.x,y=p.y+bob;ctx.save();ctx.shadowColor="#22d3ee";ctx.shadowBlur=18;ctx.strokeStyle="#67e8f9";ctx.fillStyle="#22d3ee";ctx.lineWidth=9;ctx.lineCap="round";if(squat){ctx.beginPath();ctx.arc(x,y-42,13,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(x,y-28);ctx.lineTo(x+24,y-18);ctx.lineTo(x+42,y-5);ctx.stroke();ctx.beginPath();ctx.moveTo(x+18,y-16);ctx.lineTo(x-10,y-4);ctx.stroke()}else{ctx.beginPath();ctx.arc(x,y-94,14,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(x,y-78);ctx.lineTo(x,y-37);ctx.stroke();const swing=Math.sin(t*12)*22;ctx.beginPath();ctx.moveTo(x,y-68);ctx.lineTo(x+swing,y-45);ctx.moveTo(x,y-38);ctx.lineTo(x-swing,y);ctx.moveTo(x,y-38);ctx.lineTo(x+swing,y);ctx.stroke()}ctx.restore()}

function drawMonster(ctx,m,t,misses){const x=m.x,y=414;const sway=Math.sin(t*8)*7;ctx.save();ctx.shadowColor="#ef4444";ctx.shadowBlur=14+misses*7;ctx.fillStyle="#38122d";ctx.strokeStyle="#fb7185";ctx.lineWidth=12;ctx.lineCap="round";ctx.beginPath();ctx.arc(x,y-112,30,Math.PI,0);ctx.lineTo(x+28,y-42);ctx.lineTo(x-27,y-42);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(x-18,y-75);ctx.lineTo(x-42-sway,y-45);ctx.moveTo(x+18,y-75);ctx.lineTo(x+42+sway,y-45);ctx.moveTo(x-13,y-38);ctx.lineTo(x-30+sway,y);ctx.moveTo(x+13,y-38);ctx.lineTo(x+30-sway,y);ctx.stroke();ctx.fillStyle="#fef08a";ctx.fillRect(x-15,y-112,8,5);ctx.fillRect(x+8,y-112,8,5);ctx.restore()}

function drawObstacle(ctx,o){ctx.save();if(o.resolved)ctx.globalAlpha=.35;if(o.type===OBSTACLE_TYPES.JUMP_OVER){ctx.shadowColor="#22d3ee";ctx.shadowBlur=20;ctx.fillStyle="#155e75";roundedRect(ctx,o.x,350,54,64,8);ctx.fillStyle="#67e8f9";ctx.fillRect(o.x+8,358,38,6)}else{ctx.shadowColor="#e879f9";ctx.shadowBlur=20;ctx.fillStyle="#701a75";roundedRect(ctx,o.x,250,34,164,8);roundedRect(ctx,o.x-42,250,118,28,8);ctx.fillStyle="#f0abfc";ctx.fillRect(o.x-34,258,102,5)}ctx.restore()}

export function renderFrame(ctx,state){ctx.clearRect(0,0,ctx.canvas.width,ctx.canvas.height);drawBackground(ctx,state);drawMonster(ctx,state.monster,state.elapsed,state.misses);for(const obstacle of state.obstacles)drawObstacle(ctx,obstacle);drawRunner(ctx,state.player,state.elapsed);if(state.phase==="game-over"){ctx.fillStyle="rgba(9,7,22,.58)";ctx.fillRect(0,0,ctx.canvas.width,ctx.canvas.height);ctx.textAlign="center";ctx.fillStyle="#fda4af";ctx.font="800 48px system-ui";ctx.fillText("CAUGHT!",ctx.canvas.width/2,ctx.canvas.height/2)}}
