import {describe,expect,it} from "vitest";
import {supportedMovements,challengeTemplateByMovement,type SupportedMovement,workoutPlanSchema,adventureBlueprintSchema} from "@/contracts";
import {createMissionController} from "./missionController";

function mission(movements:readonly SupportedMovement[]=supportedMovements){
 const workout=workoutPlanSchema.parse({schemaVersion:1,id:"all-moves",goal:"general",durationMinutes:20,difficulty:2,exercises:movements.map((movement,index)=>({id:`exercise-${index}`,movement,mode:movement==="plank"?"hold":"reps",target:1}))});
 const adventure=adventureBlueprintSchema.parse({schemaVersion:1,id:"all-adventure",workoutPlanId:workout.id,theme:"volcano-escape",title:"Registry Run",segments:workout.exercises.map((exercise,index)=>({id:`segment-${index}`,exerciseId:exercise.id,challengeTemplate:challengeTemplateByMovement[exercise.movement],target:1,order:index+1})),rewards:{baseXp:100}});
 return {workout,adventure};
}
describe("mission controller",()=>{
 it("maps every registered movement to objective progress and completes",()=>{const {workout,adventure}=mission();const controller=createMissionController(workout,adventure);controller.start();for(const movement of supportedMovements){expect(controller.consume({movement,phase:movement==="plank"?"held":"completed",confidence:1,occurredAtMs:1})).toBe(true);}expect(controller.getSnapshot()).toMatchObject({status:"complete",missionProgress:100});});
 it("ignores wrong movement and tolerates misses through recovery",()=>{const {workout,adventure}=mission(["squat"]);const c=createMissionController(workout,adventure);c.start();expect(c.consume({movement:"jump",phase:"completed",confidence:1,occurredAtMs:1})).toBe(false);c.recordMiss();c.recordMiss();expect(c.getSnapshot().status).toBe("playing");c.recordMiss();expect(c.getSnapshot().status).toBe("recovery");c.resume();expect(c.getSnapshot()).toMatchObject({status:"playing",misses:0});});
 it("pauses, resumes, replays, and emits coarse snapshots",()=>{const {workout,adventure}=mission(["jump"]);const c=createMissionController(workout,adventure);let updates=0;c.subscribe(()=>updates++);c.start();c.pause("Camera lost.");expect(c.getSnapshot()).toMatchObject({status:"paused",pauseReason:"Camera lost."});c.resume();c.consume({movement:"jump",phase:"completed",confidence:.9,occurredAtMs:2});expect(c.getSnapshot().status).toBe("complete");c.replay();expect(c.getSnapshot().status).toBe("ready");expect(updates).toBe(5);});
 it("preserves earned progress across camera-loss pause and retry",()=>{const {workout,adventure}=mission(["squat","jump"]);const c=createMissionController(workout,adventure);c.start();c.consume({movement:"squat",phase:"completed",confidence:.9,occurredAtMs:1});const earned=c.getSnapshot();expect(earned).toMatchObject({segmentIndex:1,missionProgress:50,xpEarned:10});c.pause("Camera disconnected.");expect(c.getSnapshot()).toMatchObject({status:"paused",segmentIndex:1,missionProgress:50,xpEarned:10});c.resume();expect(c.getSnapshot()).toMatchObject({status:"playing",segmentIndex:1,missionProgress:50,xpEarned:10,pauseReason:null});c.consume({movement:"jump",phase:"completed",confidence:.9,occurredAtMs:2});expect(c.getSnapshot()).toMatchObject({status:"complete",missionProgress:100});});
});
